name: bloodwave
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # UI & Utility
  cupertino_icons: ^1.0.8
  device_preview: ^1.3.1
  shared_preferences: ^2.2.3
  font_awesome_flutter: ^10.7.0
  google_fonts: ^6.2.1

  # Firebase (🔥 with compatible versions)
  firebase_core: ^3.0.0
  firebase_auth: ^5.6.2
  cloud_firestore: ^5.6.0
  firebase_messaging: ^15.0.0 
  flutter_local_notifications: ^17.2.2
  rxdart: ^0.28.0

  # Google Sign-In
  uuid: ^4.5.1
  firebase_storage: ^12.4.9
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/bloodwave.png"  

flutter:
  uses-material-design: true
