// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  
  static const FirebaseOptions web = FirebaseOptions(
  apiKey: 'AIzaSyCc8H-V1JO-1gtbkgyTsuwf5IvLsNVnPNM',
  appId: '1:610630473879:web:5269ef8b04835eed94f1d2',
  messagingSenderId: '610630473879',
  projectId: 'bloodwave-94715',
  authDomain: 'bloodwave-94715.firebaseapp.com',
  storageBucket: 'bloodwave-94715.appspot.com', // ✅ Corrected
);
static const FirebaseOptions android = FirebaseOptions(
  apiKey: 'AIzaSyA6FuCXHw2thQbZpY_d4mOYbVqwguwfcK0',
  appId: '1:610630473879:android:658cdc03269ce0d994f1d2',
  messagingSenderId: '610630473879',
  projectId: 'bloodwave-94715',
  storageBucket: 'bloodwave-94715.appspot.com', // ✅ Corrected
);

static const FirebaseOptions ios = FirebaseOptions(
  apiKey: 'AIzaSyDFW1YGYRpEA3OE3o39-wddf7PPZ1bEPGk',
  appId: '1:610630473879:ios:fdd4d9677687c02b94f1d2',
  messagingSenderId: '610630473879',
  projectId: 'bloodwave-94715',
  storageBucket: 'bloodwave-94715.appspot.com', // ✅ Corrected
  iosBundleId: 'com.example.bloodwave',
);



}